name: Deploy Container Image to Azure App Service

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory : src
    steps:
    #checkout the repo
    - name : 'Chekcout Github Action'
      uses : actions/checkout@main

    - name : 'Login via Azure CLI'
      uses : azure/login@v1
      with:
        creds: ${{ secrets.MYREPO }}


    - uses: azure/docker-login@v1
      with:
        login-server: 2024registry.azurecr.io
        username: 2024Registry
        password: vRTiEmt0Aa5yn6XbugLqfi0sannFD+w9sFtAWZu7wN+ACRDUqbS2
      
    - run: |
        docker build . -t 2024registry.azurecr.io/mypythonapp_cli:latest
        docker push 2024registry.azurecr.io/mypythonapp_cli:latest


    - run:
        az containerapp up --name "mypythonappcli" --resource-group "2024RG" --environment "managedEnvironment-2024RG-864b" --image "2024registry.azurecr.io/mypythonapp_cli" --target-port 3500 --ingress 'external' --registry-server "2024registry.azurecr.io" --query properties.configuration.ingress.fqdn
    - name : Azure Logout
      run:
        az logout
